import type { Metadata } from "next";
import Header from "./_components/Header";
import localFont from "next/font/local";
import "./globals.css";
import {
  ClerkProvider
} from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";

// Fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

//元数据 包含了网页的标题和描述。优化seo 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout 组件,展示要显示的内容
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme=''>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider>
          <Header />
          <Toaster/>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
